---
- hosts: pipelines
  become: yes

  tasks:
    - include_vars: pipelines_variables.yml

    - name: install fail2ban
      apt: pkg=fail2ban state=present

    - name: add deploy user
      user: name=deploy shell=/bin/bash password={{ deploy_pass }}

    - name: add ssh dir
      file: path=/home/deploy/.ssh state=directory owner=deploy group=deploy mode=0700

    - name: copy ssh deploy key files
      become_user: deploy
      copy: src=~/.ssh/deploy dest=/home/deploy/.ssh/
      
    - name: Allow deploy to have sudo
      lineinfile: dest=/etc/sudoers state=present line='deploy  ALL=(ALL:ALL) ALL'

    - name: change perms for ssh
      file: path=/home/deploy/.ssh/deploy owner=deploy group=deploy mode=0400 
    
    - name: change sshd
      copy: src=templates/sshd_config dest=/etc/ssh/sshd_config
      notify:
          - restart ssh

    - name: install hdf5
      apt: pkg=libhdf5-dev state=present install_recommends=yes
    
    - name: install hdf5 tools
      apt: pkg=hdf5-tools state=present install_recommends=yes

    - name: install sqlite
      apt: pkg=sqlite3 state=present

    - name: npm
      apt: name=npm state=present
          
    - name: nodejs
      apt: name=nodejs-legacy state=present

    - name: install npm http proxy
      npm: name=configurable-http-proxy global=yes state=present

    - name: install python crypto
      apt: name=python-cryptography state=present install_recommends=yes
      
    - name: install certbot
      apt: name=certbot state=present install_recommends=yes
    
    - name: install letsencrypt
      apt: name=letsencrypt state=present install_recommends=yes

    - name: rabbitmq
      apt: name=rabbitmq-server state=present

    - name: libmysqlclient-dev
      apt: name=libmysqlclient-dev state=present

    - name: redis
      apt: name=redis-server state=present

    - name: graphviz
      apt: name=graphviz state=present

    - name: git
      apt: name=git state=present

    - name: change app perms to fetch
      file: path=/var/www/pipelines mode=0777 recurse=yes state=directory
      ignore_errors: yes

    - name: fetch application
      become_user: deploy
      git: repo=https://github.com/jeasung-pf/data-pipelines-course.git dest=/var/www/pipelines

    - name: install requirements
      pip: requirements=/var/www/pipelines/requirements.txt virtualenv_python=/home/ubuntu/anaconda3/envs/python3/bin/python  virtualenv=/home/deploy/venv
      environment: 
          HDF5_DIR: /usr/lib/x86_64-linux-gnu/hdf5/serial/  

    - name: make notebooks directory 
      file: path=/var/www/pipelines/notebooks state=directory owner=deploy mode=0755 recurse=yes
    
    - name: make notebooks cookiefile 
      file: path=/var/www/pipelines/notebooks/jupyterhub_cookie_secret mode=0600 state=touch
  
    - name: make celery config directory 
      file: path=/var/www/pipelines/celery_app/config state=directory owner=deploy mode=0755 recurse=yes
      
    - name: copy config to celery dir
      copy: src=../celery_app/config/prod.cfg dest=/var/www/pipelines/celery_app/config

    - name: copy config to nb dir
      copy: src=templates/jupyterhub_config.py dest=/var/www/pipelines/notebooks

    - name: make log dir
      file: path=/var/log/celery state=directory owner=deploy mode=0755 recurse=yes

    - name: rabbitmq add vhost
      rabbitmq_vhost: name=celery_vhost state=present

    - name: add rabbitmq user
      rabbitmq_user: user=celery_user password={{ rabbitmq_pass }} vhost=celery_vhost configure_priv=.* read_priv=.* write_priv=.* tags=administrator state=present

    - name: enabling rabbitmq management 
      rabbitmq_plugin: names=rabbitmq_management state=enabled
      notify:
          - restart rabbitmq

    - name: change sysd perms
      file: path=/var/www/pipelines/deploy mode=0644 recurse=yes

    - name: link flower systemd file
      file: src=/var/www/pipelines/deploy/flower_service dest=/etc/systemd/system/flower.service state=link

    - name: link celery systemd file
      file: src=/var/www/pipelines/deploy/celery_service dest=/etc/systemd/system/celery.service state=link
   
    - name: link celerybeat systemd file
      file: src=/var/www/pipelines/deploy/celerybeat_service dest=/etc/systemd/system/celerybeat.service state=link

    - name: link jupyterhub systemd file
      file: src=/var/www/pipelines/deploy/jupyterhub_service dest=/etc/systemd/system/jupyterhub.service state=link
    
    #- name: link jupyter systemd file
    #  file: src=/var/www/pipelines/deploy/jupyter_service dest=/etc/systemd/system/jupyterhub.service state=link

    - name: reload systemd
      shell: systemctl daemon-reload && systemctl restart jupyterhub

    - name: start flower & celery & celerybeat
      shell: systemctl restart celery && systemctl restart flower && systemctl restart celerybeat
  
  handlers:
    - name: restart rabbitmq
      service: name=rabbitmq-server state=restarted

    - name: restart ssh
      service: name=ssh state=restarted
